const constants = {
    SET_SELECTED_TAB: 'SET_SELECTED_TAB',
    SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
    SET_SELECTED_MODAL_TAB: 'SET_SELECTED_MODAL_TAB',
    SET_SELECTED_AUTHORIZATION_TAB: 'SET_SELECTED_AUTHORIZATION_TAB',
    SET_ITEMS: 'SET_ITEMS',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    SET_COUNTERS_VALUE: 'SET_COUNTERS_VALUE',
    SET_ORDER_ITEMS: 'SET_ORDER_ITEMS',
    SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
    SET_MODAL_WINDOW_ADD_SHOW: 'SET_MODAL_WINDOW_ADD_SHOW',
    SET_MODAL_WINDOW_EDIT_SHOW: 'SET_MODAL_WINDOW_EDIT_SHOW',
    SET_MODAL_WINDOW_AUTHORIZATION_SHOW: 'SET_MODAL_WINDOW_AUTHORIZATION_SHOW',
    SET_MODAL_CONTENT: 'SET_MODAL_CONTENT',
    SET_SANDWICHES: 'SET_SANDWICHES',
    SET_TAB_READY_CONTENT: 'SET_TAB_READY_CONTENT',
    SET_CHANGEABLE_ORDER_ITEM: 'SET_CHANGEABLE_ORDER_ITEM',
    SET_PREVIOUS_VALUES: 'SET_PREVIOUS_VALUES',
    SET_ITEMS_INFO: 'SET_ITEMS_INFO'
  }
  
  export default constants;